"""
RC Low-Pass / High-Pass Filter
================================
Transfer function:
  LP:  H(s) = 1/(1+sRC)      fc = 1/(2πRC)
  HP:  H(s) = sRC/(1+sRC)    fc = 1/(2πRC)

Design strategy:
  Grid-search R over E24 practical range [1 kΩ … 470 kΩ].
  For each R, derive C = 1/(2π·fc·R), snap C to E12, re-evaluate.
  Pick the (R, C) pair that minimises |fc_achieved - fc_target|.
  Practical R range keeps C in a sensible range (pF to hundreds of µF).
"""

import numpy as np
from circuits.base import BaseCircuit
from circuits._fmt import _fmt_r, _fmt_c
from core.models import DesignSpec, DesignResult
from solvers.e_series import nearest_e24, nearest_e12_cap

_E24_BASE = [1.0,1.1,1.2,1.3,1.5,1.6,1.8,2.0,
             2.2,2.4,2.7,3.0,3.3,3.6,3.9,4.3,
             4.7,5.1,5.6,6.2,6.8,7.5,8.2,9.1]

# Practical R range for RC filters: 1 kΩ – 470 kΩ
_E24_R_FILTER = [round(b * 10**e, 4)
                 for e in range(3, 6)       # 1 kΩ … 100 kΩ decade
                 for b in _E24_BASE] + \
                [round(b * 1e5, 4) for b in _E24_BASE if b <= 4.7]  # up to 470 kΩ


class RCFilter(BaseCircuit):

    FILTER_TYPES = {"low_pass", "high_pass"}

    def __init__(self, spec: DesignSpec):
        super().__init__(spec)
        self.fc    = float(spec.get("cutoff_frequency", 1e3))
        raw_type   = spec.params.get("filter_type", "low_pass")
        self.ftype = str(raw_type).lower().replace("-", "_").replace(" ", "_")
        self.RL    = float(spec.get("load_resistance", 10e3))

        if self.ftype not in self.FILTER_TYPES:
            raise ValueError(
                f"filter_type must be one of {self.FILTER_TYPES}, got '{self.ftype}'"
            )
        if self.fc <= 0:
            raise ValueError("cutoff_frequency must be > 0 Hz")

    def optimize(self) -> DesignResult:
        best_R   = None
        best_C   = None
        best_err = np.inf

        for R in _E24_R_FILTER:
            C_ideal = 1.0 / (2 * np.pi * self.fc * R)

            # Reject capacitors outside practical range  (10 pF … 1000 µF)
            if not (10e-12 <= C_ideal <= 1000e-6):
                continue

            C_std  = nearest_e12_cap(C_ideal)
            fc_ach = 1.0 / (2 * np.pi * R * C_std)
            err    = abs(fc_ach - self.fc) / self.fc

            if err < best_err:
                best_err = err
                best_R   = R
                best_C   = C_std

        if best_R is None:
            raise RuntimeError(
                f"No valid R/C pair found for fc={self.fc:.1f} Hz. "
                "Check that fc is between 0.1 Hz and 10 MHz."
            )

        fc_ach  = 1.0 / (2 * np.pi * best_R * best_C)
        err_pct = abs(fc_ach - self.fc) / self.fc * 100

        warnings = []
        if err_pct > 5.0:
            warnings.append(
                f"fc error {err_pct:.1f}% – E12 cap quantisation limit; "
                "consider a trimmer or non-standard value."
            )

        return DesignResult(
            circuit_type="rc_filter",
            component_values={"R": best_R, "C": best_C, "RL": self.RL},
            operating_point={},
            achieved_performance={"fc (Hz)": fc_ach},
            target_performance={"fc (Hz)": self.fc},
            optimization_error=float(best_err),
            warnings=warnings,
        )

    def netlist_lines(self, result: DesignResult) -> list[str]:
        cv  = result.component_values
        R   = cv["R"]
        C   = cv["C"]
        RL  = cv["RL"]
        fc  = result.achieved_performance.get("fc (Hz)", 0)

        title = self.ftype.replace("_", " ").title()

        if self.ftype == "low_pass":
            comment  = "* Topology:  Vin --[R]-- Vout --[C]-- GND"
            r_line   = f"R1   in   out  {_fmt_r(R)}"
            c_line   = f"C1   out  0    {_fmt_c(C)}"
        else:  # high_pass
            comment  = "* Topology:  Vin --[C]-- Vout --[R]-- GND"
            r_line   = f"R1   out  0    {_fmt_r(R)}"
            c_line   = f"C1   in   out  {_fmt_c(C)}"

        f_start = max(self.fc / 100, 0.1)
        f_stop  = self.fc * 100

        return [
            f"* RC {title} Filter",
            f"* Target fc = {self.fc:.2f} Hz  |  Achieved fc \u2248 {fc:.2f} Hz",
            "* Generated by Python EDA System",
            "",
            comment,
            "",
            f"Vin  in   0  AC 1  SIN(0 1 {self.fc:.2f})",
            r_line,
            c_line,
            f"RL   out  0  {_fmt_r(RL)}",
            "",
            ".OP",
            f".AC DEC 100 {f_start:.4g} {f_stop:.4g}",
            ".END",
        ]
